### ISSUE TITLE
safely use global

### ISSUE THREAD

**Issue by ibreathebsb** [ljharb/has-symbols#4]
in the source code

```js
var origSymbol = global.Symbol;

```

i think this one better
```js
var origSymbol = global && global.Symbol;

```

**Comment by ljharb** [comment]
Why? It’s a node module. global can’t ever not exist.

**Comment by oles** [comment]
Uh-oh.

`import 'array.prototype.find'`

results in: `ReferenceError: global is not defined`
traced to: `var origSymbol = global.Symbol;`

```
$ npm ls has-symbols
└─┬ array.prototype.find@2.1.0
  └─┬ es-abstract@1.13.0
    └─┬ es-to-primitive@1.2.0
      └─┬ is-symbol@1.0.2
        └── has-symbols@1.0.0
```

@ljharb is it better to handle the issue here or in https://github.com/es-shims/Array.prototype.find?

**Comment by ibreathebsb** [comment]
@oles  I hacked this by using `file://` protocol, make a package that has the same name in you project , maybe this will help

package.json 

```json
{

"dependencies": {
    "has-symbols": "file:./src/pollyfill/has-symbols"
  }
}

```
in the directory `./src/pollyfill/has-symbols`, there are three files: 
├── README.MD
├── index.js
└── package.json


```js
module.exports = function hasSymbols() {
  return false
}

```

**Comment by ljharb** [comment]
@oles global is always defined in node; are you using a bundler that doesn’t define it?

**Comment by oles** [comment]
Should have noted that this happened in Firefox, where the usecase is polyfilling Array.prototype.find (and .flat). Sorry for missing this vital information, @ljharb!

**Comment by oles** [comment]
I'm using webpack, let me check my config tomorrow!

**Comment by ljharb** [comment]
Webpack absolutely understands global by default or it wouldn’t be able to bundle most of npm.

**Comment by oles** [comment]
Aha. I've set `node: false` in my config. Removing that solves this!

Though this might not be the case in the future?
https://github.com/webpack/changelog-v5/blob/master/README.md#automatic-nodejs-polyfills-removed

Thanks for the help, @ljharb!

**Comment by ljharb** [comment]
I doubt the global polyfill, which is a single line (`global = window`), will be excluded there, but certainly if webpack changes its approach then that may impose difficulty on its users.

**Comment by boris-petrov** [comment]
@ljharb - I also hit the same problem in a browser environment. Bundler is webpack with `node: false`. Stacktrace:

```
index.js:3 Uncaught (in promise) ReferenceError: global is not defined
    at Object../node_modules/has-symbols/index.js
    at Object../node_modules/es-abstract/GetIntrinsic.js
    at Object../node_modules/es-abstract/es5.js
    at Object../node_modules/string.prototype.trim/implementation.js
    at Object../node_modules/string.prototype.trim/index.js
    at Object../node_modules/parse-headers/parse-headers.js
    at Object../node_modules/xhr/index.js
    at Module../node_modules/video.js/dist/video.es.js
```

That is, I'm using `video.js` which is a browser package and it transitively includes `has-symbols`, which blows up because `global` is not defined.

Why don't you just make `has-symbols` browser-friendly? :)

**Comment by ljharb** [comment]
@boris-petrov it is browser-friendly; `node: false` is what's not browser-friendly.

I could certainly use https://www.npmjs.com/package/globalthis instead of relying on `global` being present, but that would be *un*friendly to users in a CSP environment, and would also inflate the bundle size further.

**Comment by boris-petrov** [comment]
@ljharb - I don't want to argue too much because polyfilling `global` is a single line of code but if you open the console in your browser right now and type `global` in it you'll get a `global is not defined` error. :) So adding `node: false` doesn't make it browser-unfriendly, it makes it "correct". I agree that it would inflate the bundle size but... that's the way JavaScript works unfortunately.

Again, feel free to ignore my comment as it is not a big deal, but I believe that right now the behavior is not correct.

Thank you for the time!

**Comment by ljharb** [comment]
You’re totally right that global doesn’t work in a browser - but by default, any npm package that uses global (and there are a great many) is transpiled to use window by every bundler. Using node: false is *disabling* that default and thus deviating from community convention.

require doesn’t work in the browser either, but i don’t see you complaining about the use of require - this is a node module, and “browser friendly” for all node modules means “transpiles the way browserify does by default”.

**Comment by boris-petrov** [comment]
OK, fair enough! Thanks again!

**Comment by Knagis** [comment]
https://docs.npmjs.com/files/package.json#browser

You can specify a separate implementation for node and browser environments - this way your package would work out of the box for both and neither includes code that is not needed.

As pointed out in a comment above, webpack 5 no longer transpiles `global` to `window` by default so you might see duplicates of this issue popping up more often once they get out of beta.

**Comment by ljharb** [comment]
Webpack 5 isn’t out yet, and i still hope to convince them to restore the proper behavior of transpiling global to window.

You’re right that i could duplicate the entire file just to change global to window, but since every bundler window the beginning of node has done that, it seems like a strange redundancy to force on the entire ecosystem.

**Comment by bhushanlaware** [comment]
still getting this issue, can't we use globalThis instead global?

**Comment by ljharb** [comment]
@bhushanlaware no, can’t we use non-broken bundlers instead of broken ones?
